language: python

python:
  - "2.7"

install:
  - pip install coverage
  - python setup.py develop easy_install kmltrack[cli,msgpack,test]

script:
  - nosetests --with-coverage

after_success:
  - coveralls
